
migrate:
	npx run db:migrate

push:
	npx run db:push

view-db:
	npx prisma studio

dev:
	npx run dev

clean:
	rm -rf prisma/db
	rm -rf ./dist
	rm -rf node_modules
	rm -rf uploads/*
	rm -rf coverage


lint:
	npx eslint .
